# Generated by Django 5.2.15 on 2026-07-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("agreement", "Agreement"),
                            ("notice", "Notice"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=32)),
                ("active", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_documents",
                        related_query_name="legal_document",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active", "document_type", "-published_at"],
                        name="legal_legal_active_364d68_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "version"),
                        name="legal_document_unique_type_version",
                    )
                ],
            },
        ),
    ]
