# Generated by Django 5.2.15 on 2026-07-07 14:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("release_date", models.DateField()),
                ("active", models.BooleanField(default=False)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "All employees"),
                            ("new_hires", "New hires"),
                            ("managers", "Managers"),
                        ],
                        default="all",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active", "release_date"],
                        name="onboarding__active_4c2d11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ViewedOnboardingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewed_onboarding_items",
                        related_query_name="viewed_onboarding_item",
                        to="employees.employee",
                    ),
                ),
                (
                    "onboarding_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        related_query_name="view",
                        to="onboarding.onboardingitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "viewed_at"],
                        name="onboarding__employe_cd4793_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "onboarding_item"),
                        name="unique_viewed_onboarding_item",
                    )
                ],
            },
        ),
    ]
