# Generated by Django 5.2.15 on 2026-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_id__isnull", True),
                    models.Q(("parent_id", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="department_parent_is_not_self",
            ),
        ),
    ]
