# Generated by Django 5.2.15 on 2026-07-07 12:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("login", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, max_length=150)),
                ("position", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("is_phone_visible", models.BooleanField(default=False)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("is_birthdate_visible", models.BooleanField(default=False)),
                ("telegram_username", models.CharField(blank=True, max_length=64)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("about", models.TextField(blank=True, max_length=2500)),
                ("hobbies", models.TextField(blank=True, max_length=2500)),
                ("education", models.CharField(blank=True, max_length=255)),
                (
                    "current_photo",
                    models.FileField(blank=True, upload_to="employees/current_photos/"),
                ),
                (
                    "pending_photo",
                    models.FileField(blank=True, upload_to="employees/pending_photos/"),
                ),
                (
                    "pending_photo_uploaded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("hired_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        related_query_name="employee",
                        to="org.department",
                    ),
                ),
                (
                    "hrbp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hrbp_profiles",
                        related_query_name="hrbp_profile",
                        to="employees.employee",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        related_query_name="direct_report",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="employees_e_last_na_99a4c0_idx",
                    ),
                    models.Index(
                        fields=["department", "is_active"],
                        name="employees_e_departm_fa1d35_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manager_id__isnull", True),
                            models.Q(("manager_id", models.F("id")), _negated=True),
                            _connector="OR",
                        ),
                        name="employee_manager_is_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hrbp_id__isnull", True),
                            models.Q(("hrbp_id", models.F("id")), _negated=True),
                            _connector="OR",
                        ),
                        name="employee_hrbp_is_not_self",
                    ),
                ],
            },
        ),
    ]
