# Generated by Django 5.2.15 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employee_employee_active_name_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="add_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="employee",
            name="location_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="employee",
            name="education",
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
