# Generated by Django 5.2.15 on 2026-09-07 09:19

import django.db.models.deletion
from django.db import migrations, models

import apps.employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_employee_location_fields_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pending_photo",
            field=models.FileField(
                blank=True,
                storage=apps.employees.storage.PrivatePendingPhotoStorage(),
                upload_to="employees/pending_photos/",
            ),
        ),
        migrations.CreateModel(
            name="PhotoRejectionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("reason", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivery_claimed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_rejection_notifications",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at", "created_at"],
                        name="employees_p_sent_at_ba90ea_idx",
                    )
                ],
            },
        ),
    ]
