# Generated by Django 5.2.15 on 2026-09-07 18:05

from django.db import migrations, models

import apps.employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_alter_employee_pending_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="approved_photo",
            field=models.FileField(
                blank=True,
                storage=apps.employees.storage.PrivatePendingPhotoStorage(),
                upload_to="employees/pending_photos/",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="approved_photo_promotion_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="approved_photo_public_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
